/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/LoginView': RouteRecordInfo<
      '/LoginView',
      '/LoginView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RegisterView': RouteRecordInfo<
      '/RegisterView',
      '/RegisterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workbench/': RouteRecordInfo<
      '/workbench/',
      '/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workbench/export/': RouteRecordInfo<
      '/workbench/export/',
      '/workbench/export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workbench/import/': RouteRecordInfo<
      '/workbench/import/',
      '/workbench/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workbench/query/': RouteRecordInfo<
      '/workbench/query/',
      '/workbench/query',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/LoginView.vue': {
      routes:
        | '/LoginView'
      views:
        | never
    }
    'src/views/RegisterView.vue': {
      routes:
        | '/RegisterView'
      views:
        | never
    }
    'src/views/workbench/index.vue': {
      routes:
        | '/workbench/'
      views:
        | never
    }
    'src/views/workbench/export/index.vue': {
      routes:
        | '/workbench/export/'
      views:
        | never
    }
    'src/views/workbench/import/index.vue': {
      routes:
        | '/workbench/import/'
      views:
        | never
    }
    'src/views/workbench/query/index.vue': {
      routes:
        | '/workbench/query/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
