CREATE USER app_read WITH PASSWORD 'readpass';
CREATE USER app_write WITH PASSWORD 'writepass';

GRANT CONNECT ON DATABASE sample TO app_read;
GRANT CONNECT ON DATABASE sample TO app_write;
GRANT USAGE ON SCHEMA public TO app_read;
GRANT USAGE ON SCHEMA public TO app_write;

CREATE TABLE widgets (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  qty INT NOT NULL DEFAULT 0
);

INSERT INTO widgets (name, qty) VALUES ('alpha', 3), ('beta', 7);

GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO app_read;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
